apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: python:3.11-slim
          command:
            - sh
            - -c
            - |
              pip install flask flask-cors && python /app/app.py
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: app-code
              mountPath: /app
            - name: data
              mountPath: /data
      volumes:
        - name: app-code
          configMap:
            name: backend-config
        - name: data
          persistentVolumeClaim:
            claimName: backend-pvc
