---
- name: Install Docker on all Kubernetes nodes
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Download Docker 20.10 install script
      get_url:
        url: https://releases.rancher.com/install-docker/20.10.sh
        dest: /tmp/20.10.sh
        mode: '0755'

    - name: Run Docker install script
      command: sh /tmp/20.10.sh
      args:
        creates: /usr/bin/docker

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
